<?php

declare(strict_types=1);
?>
<section class="admin-grid two-thirds">
    <div class="admin-stack">
        <form class="admin-card admin-form" method="post" action="<?= cv_admin_url('backup/export-json') ?>">
            <input type="hidden" name="_token" value="<?= cv_e(cv_csrf_token('admin')) ?>">
            <div class="admin-card-head">
                <div>
                    <h2>Backup and export</h2>
                    <p>Create a JSON snapshot of settings, blocks, and content tables without cron jobs or server access.</p>
                </div>
            </div>
            <button class="admin-button admin-button-primary" type="submit">Create JSON backup</button>
            <a class="admin-button admin-button-secondary" href="<?= cv_admin_url('backup/export-csv') ?>">Export messages CSV</a>
        </form>
        <form class="admin-card admin-form" method="post" enctype="multipart/form-data" action="<?= cv_admin_url('backup/import-json') ?>" data-confirm="Importing a backup replaces current content tables. Continue?">
            <input type="hidden" name="_token" value="<?= cv_e(cv_csrf_token('admin')) ?>">
            <div class="admin-card-head">
                <div>
                    <h2>Import from JSON</h2>
                    <p>Use only a backup generated by this panel. The importer replaces content/settings tables to restore a known state.</p>
                </div>
            </div>
            <label><span>JSON file</span><input type="file" name="import_file" accept=".json" required></label>
            <p class="field-hint">Content blocks, site settings, portfolio entities, and projects are restored. Analytics, messages, and local files are not overwritten.</p>
            <button class="admin-button admin-button-secondary" type="submit">Import backup</button>
        </form>
    </div>
    <div class="admin-card">
        <div class="admin-card-head"><h2>Stored backups</h2></div>
        <?php if ($backup_files !== []): ?>
            <div class="mini-list">
                <?php foreach ($backup_files as $file): ?>
                    <div class="mini-list-item">
                        <div class="mini-list-item-body">
                            <strong><?= cv_e(basename($file)) ?></strong>
                            <span><?= cv_e((string) date('Y-m-d H:i:s', filemtime($file))) ?></span>
                        </div>
                    </div>
                <?php endforeach; ?>
            </div>
        <?php else: ?>
            <div class="empty-state">
                <strong>No backups stored yet.</strong>
                <p>Create the first JSON snapshot before deployment or before making major content changes.</p>
            </div>
        <?php endif; ?>
    </div>
</section>
