-- Optional demo seed for PostgreSQL / Neon.
-- Run only after storage/schema.sql.

INSERT INTO admin_users (username, email, full_name, password_hash, created_at, updated_at)
VALUES
('owner', 'fakhridinkon2009@gmail.com', 'Makhmadkhonzoda Fakhriddin', '$2y$12$D7vJdI1IDR/ZS9GAgiZubuz9LdibDQXkAo6K60NIZiuhfJHXsmVJW', NOW(), NOW());

INSERT INTO site_settings (group_key, setting_key, locale_code, value_long, value_type, updated_at) VALUES
('site', 'site_name', 'ru', 'Махмадхонзода Фахриддин', 'text', NOW()),
('site', 'site_tagline', 'ru', 'Backend developer с фокусом на PHP, Go, API, админ-панели и прикладные веб-системы.', 'text', NOW()),
('site', 'primary_cta_label', 'ru', 'Обсудить задачу', 'text', NOW()),
('site', 'primary_cta_url', 'ru', '#contact', 'text', NOW()),
('site', 'secondary_cta_label', 'ru', 'Смотреть кейсы', 'text', NOW()),
('site', 'secondary_cta_url', 'ru', '#projects', 'text', NOW()),
('site', 'contact_email', 'ru', 'fakhridinkon2009@gmail.com', 'text', NOW()),
('site', 'contact_phone', 'ru', '+992 881 845 151', 'text', NOW()),
('site', 'contact_telegram', 'ru', '@Fakhriddin_dev', 'text', NOW()),
('site', 'location', 'ru', 'Гиссар, Таджикистан', 'text', NOW()),
('site', 'footer_notice', 'ru', 'Премиальное portfolio backend developer: API, web-системы, админ-панели и продуманная реализация.', 'text', NOW()),
('site', 'theme_default', 'ru', 'dark', 'text', NOW()),
('site', 'site_name', 'en', 'Makhmadkhonzoda Fakhriddin', 'text', NOW()),
('site', 'site_tagline', 'en', 'Backend developer focused on PHP, Go, APIs, admin panels, and practical web systems.', 'text', NOW()),
('site', 'primary_cta_label', 'en', 'Discuss your project', 'text', NOW()),
('site', 'primary_cta_url', 'en', '#contact', 'text', NOW()),
('site', 'secondary_cta_label', 'en', 'View case studies', 'text', NOW()),
('site', 'secondary_cta_url', 'en', '#projects', 'text', NOW()),
('site', 'contact_email', 'en', 'fakhridinkon2009@gmail.com', 'text', NOW()),
('site', 'contact_phone', 'en', '+992 881 845 151', 'text', NOW()),
('site', 'contact_telegram', 'en', '@Fakhriddin_dev', 'text', NOW()),
('site', 'location', 'en', 'Hisor, Tajikistan', 'text', NOW()),
('site', 'footer_notice', 'en', 'Premium backend portfolio with APIs, web systems, admin layers, and production-minded implementation.', 'text', NOW()),
('site', 'theme_default', 'en', 'dark', 'text', NOW()),
('social', 'telegram', '*', 'https://t.me/Fakhriddin_dev', 'text', NOW()),
('social', 'email', '*', 'mailto:fakhridinkon2009@gmail.com', 'text', NOW()),
('social', 'phone', '*', 'tel:+992881845151', 'text', NOW()),
('social', 'linkedin', '*', 'https://www.linkedin.com/in/fakhriddin-go/', 'text', NOW()),
('social', 'github', '*', 'https://github.com/fakha2009', 'text', NOW()),
('social', 'instagram', '*', '', 'text', NOW()),
('seo', 'meta_title', 'ru', 'Махмадхонзода Фахриддин | Backend Developer - Go / PHP / Python', 'text', NOW()),
('seo', 'meta_description', 'ru', 'Backend developer: Go, PHP, Python, API, PostgreSQL, MySQL, Redis, Docker и прикладные веб-системы.', 'text', NOW()),
('seo', 'og_image', 'ru', 'assets/img/og-cover.svg', 'text', NOW()),
('seo', 'twitter_card', 'ru', 'summary_large_image', 'text', NOW()),
('seo', 'robots_index', 'ru', '1', 'text', NOW()),
('seo', 'meta_title', 'en', 'Makhmadkhonzoda Fakhriddin | Backend Developer - Go / PHP / Python', 'text', NOW()),
('seo', 'meta_description', 'en', 'Backend developer focused on Go, PHP, Python, APIs, PostgreSQL, MySQL, Redis, Docker, and practical web systems.', 'text', NOW()),
('seo', 'og_image', 'en', 'assets/img/og-cover.svg', 'text', NOW()),
('seo', 'twitter_card', 'en', 'summary_large_image', 'text', NOW()),
('seo', 'robots_index', 'en', '1', 'text', NOW());

INSERT INTO content_blocks (block_key, locale_code, payload_json, status, updated_at) VALUES
('blog_intro', 'ru', '{"label":"Блог","title":"Последние мысли","text":"Записи о backend, API, админ-панелях и практических web-проектах."}', 'published', NOW()),
('blog_intro', 'en', '{"label":"Blog","title":"Latest thoughts","text":"Posts about backend, APIs, admin panels, and practical web engineering."}', 'published', NOW());

INSERT INTO blog_posts (title_ru, title_en, slug, excerpt_ru, excerpt_en, body_ru, body_en, cover_image, tags, published_at, featured, status, sort_order, created_at, updated_at) VALUES
('Новый подход к backend-практике', 'A fresh approach to backend practice', 'backend-practice', 'Практика backend должна быть понятной, документированной и применимой вне учебного шага.', 'Backend practice should be clear, documented, and applicable beyond the study phase.', 'В этой записи я рассказываю, почему backend-проекты выигрывают от строгой структуры данных, понятных API и реалистичных сценариев использования.', 'In this post I explain why backend projects benefit from strict data structure, clear APIs, and realistic usage scenarios.', 'assets/img/blog-backend.svg', 'backend,api,practice', NOW(), 1, 'published', 1, NOW(), NOW()),
('API и UX developer experience', 'API and developer experience', 'api-developer-experience', 'Хороший API — это не только данные, но и удобство работы с ним для разработчика.', 'A good API is not only about data but also developer usability.', 'Хороший API учитывает ошибки, валидацию, документацию и понятное поведение при нестандартных запросах.', 'A good API takes errors, validation, docs, and sensible behavior for edge requests into account.', 'assets/img/blog-api.svg', 'api,developer,ux', NOW(), 0, 'published', 2, NOW(), NOW());

INSERT INTO skills (group_ru, group_en, title_ru, title_en, description_ru, description_en, skill_level, icon, sort_order, status, created_at, updated_at) VALUES
('Языки', 'Languages', 'Go', 'Go', 'Использую Go для API, учебных сервисов и небольших backend-инструментов, где важны ясность и спокойная структура.', 'I use Go for APIs, study services, and smaller backend tools where clarity and structure matter.', 'Core', 'go', 1, 'published', NOW(), NOW()),
('Языки', 'Languages', 'PHP', 'PHP', 'Использую PHP для production-minded веб-систем, форм, админ-панелей и серверной логики.', 'I use PHP for production-minded web systems, forms, admin panels, and server-side logic.', 'Core', 'php', 2, 'published', NOW(), NOW()),
('Языки', 'Languages', 'Python', 'Python', 'Применяю Python для утилит, автоматизации и небольших технических сценариев.', 'I use Python for utilities, automation, and smaller technical workflows.', 'Applied', 'py', 3, 'published', NOW(), NOW()),
('Backend', 'Backend', 'REST API', 'REST API', 'Проектирую и реализую API с понятной структурой, предсказуемым поведением и аккуратной обработкой запросов.', 'I build REST APIs with clear structure, predictable behavior, and careful request handling.', 'Core', 'api', 4, 'published', NOW(), NOW()),
('Backend', 'Backend', 'HTTP', 'HTTP', 'Понимаю клиент-серверную модель, маршрутизацию, обработку запросов и взаимодействие между слоями приложения.', 'Comfortable with client-server flow, routing, request handling, and interaction between application layers.', 'Core', 'http', 5, 'published', NOW(), NOW()),
('Backend', 'Backend', 'SQL', 'SQL', 'Работаю с SQL-запросами, выборками, фильтрацией и прикладной логикой данных.', 'I work with SQL queries, filtering, data retrieval, and practical data logic.', 'Core', 'sql', 6, 'published', NOW(), NOW()),
('Базы данных', 'Databases', 'PostgreSQL', 'PostgreSQL', 'Использую PostgreSQL в backend-кейсах, где важны структура данных, фильтрация и надежная работа с сущностями.', 'I use PostgreSQL in backend case studies where data structure, filtering, and reliable entity handling matter.', 'Core', 'pg', 7, 'published', NOW(), NOW()),
('Базы данных', 'Databases', 'MySQL', 'MySQL', 'Использую MySQL в веб-проектах, CRUD-сценариях, настройках сайта и админских интерфейсах.', 'I use MySQL in web projects, CRUD scenarios, site settings, and admin-oriented interfaces.', 'Core', 'my', 8, 'published', NOW(), NOW()),
('Базы данных', 'Databases', 'Redis', 'Redis', 'Работаю с Redis в практических backend-сценариях, где нужен быстрый доступ к служебным данным.', 'I use Redis in practical backend flows where fast access to supporting data is useful.', 'Applied', 'rd', 9, 'published', NOW(), NOW()),
('Инструменты', 'Tools', 'Docker', 'Docker', 'Использую Docker для упаковки и повторяемого запуска учебных и прикладных проектов.', 'I use Docker to package and run study and applied projects in a repeatable way.', 'Applied', 'dk', 10, 'published', NOW(), NOW()),
('Инструменты', 'Tools', 'Git', 'Git', 'Использую Git как базовый инструмент контроля изменений и аккуратной итеративной разработки.', 'I use Git as the standard tool for version control and steady iterative development.', 'Core', 'git', 11, 'published', NOW(), NOW()),
('Инженерный подход', 'Engineering approach', 'Поддерживаемость', 'Maintainability', 'Стараюсь собирать решения так, чтобы их было легче читать, поддерживать и развивать дальше.', 'I aim to build solutions that stay easier to read, maintain, and extend over time.', 'Approach', 'mt', 12, 'published', NOW(), NOW()),
('Инженерный подход', 'Engineering approach', 'Практичность решения', 'Practical problem solving', 'Фокусируюсь на логике, пользе и рабочем результате, а не на лишней сложности.', 'I focus on logic, usefulness, and working outcomes instead of unnecessary complexity.', 'Approach', 'ps', 13, 'published', NOW(), NOW());

INSERT INTO services (title_ru, title_en, description_ru, description_en, cta_ru, cta_en, accent, sort_order, status, created_at, updated_at) VALUES
('Backend-разработка', 'Backend development', 'Серверная логика, API, бизнес-правила, обработчики, данные и прикладные сценарии для web-систем.', 'Server-side logic, APIs, business rules, data handling, and practical workflows for web systems.', 'API, логика, интеграции', 'APIs, logic, integrations', '#93F5B2', 1, 'published', NOW(), NOW()),
('API и интеграции', 'API development and integrations', 'REST API, внешние и внутренние интеграции, соединение сервисов, форм и клиентских интерфейсов.', 'REST APIs, internal and external integrations, and the connection between services, forms, and client-facing interfaces.', 'Связанные backend-сценарии', 'Connected backend flows', '#7CC8FF', 2, 'published', NOW(), NOW()),
('Сайты и admin-панели', 'Websites and admin panels', 'Бизнес-сайты, панели управления, CRUD-сценарии и внутренние интерфейсы с понятной структурой.', 'Business websites, control panels, CRUD workflows, and internal interfaces with clear structure.', 'Сайт + control layer', 'Website + control layer', '#D7FF8E', 3, 'published', NOW(), NOW()),
('Утилиты и автоматизация', 'Automation tools and utilities', 'Небольшие решения на Go и Python для автоматизации действий, работы с данными и внутренних процессов.', 'Small Go and Python solutions for workflow automation, data handling, and internal processes.', 'Практичные внутренние инструменты', 'Practical internal tooling', '#A7D8FF', 4, 'published', NOW(), NOW()),
('Data-driven веб-решения', 'Data-driven web solutions', 'Веб-продукты и backend-сценарии, где важны формы, фильтры, статусы, данные и аккуратная логика.', 'Web products and backend workflows where forms, filtering, statuses, data, and careful logic matter.', 'Данные, фильтры, логика', 'Data, filters, logic', '#C9F4B8', 5, 'published', NOW(), NOW());

INSERT INTO faqs (question_ru, question_en, answer_ru, answer_en, sort_order, status, created_at, updated_at) VALUES
('С какими технологиями вы работаете?', 'What technologies do you work with?', 'Основной публичный стек: Go, PHP, Python, PostgreSQL, MySQL, Redis, REST API, HTTP, SQL, Docker и Git.', 'My public stack includes Go, PHP, Python, PostgreSQL, MySQL, Redis, REST API, HTTP, SQL, Docker, and Git.', 1, 'published', NOW(), NOW()),
('Вы работаете только с backend?', 'Do you work only on backend?', 'Основной фокус у меня на backend, API и серверной логике, но при необходимости я также собираю связанный web-интерфейс и административную часть.', 'My main focus is backend, APIs, and server-side logic, but I can also build the connected web interface and admin layer when needed.', 2, 'published', NOW(), NOW()),
('Можно ли собрать сайт с админ-панелью?', 'Can you build a website with an admin panel?', 'Да. Я могу собрать сайт, формы, CRUD-логику, скрытую admin-панель и связанный backend-слой как единое решение.', 'Yes. I can build the site, forms, CRUD logic, a hidden admin panel, and the connected backend layer as one solution.', 3, 'published', NOW(), NOW()),
('Открыты ли вы к проектной работе?', 'Are you open to project work?', 'Да. Открыт к сотрудничеству, проектной работе и задачам, где важны backend, API, web-системы и прикладная логика.', 'Yes. I am open to collaboration and project work where backend, APIs, web systems, and practical logic matter.', 4, 'published', NOW(), NOW()),
('Как лучше связаться с вами?', 'What is the best way to contact you?', 'Через форму на сайте, по email, по телефону или в Telegram: @Fakhriddin_dev.', 'Through the website form, by email, by phone, or on Telegram: @Fakhriddin_dev.', 5, 'published', NOW(), NOW());

INSERT INTO project_categories (name_ru, name_en, slug, description_ru, description_en, sort_order, status, created_at, updated_at) VALUES
('Практические проекты', 'Practice projects', 'practice-projects', 'Практические и учебные кейсы, где важны логика, структура данных и рабочие backend-сценарии.', 'Practice and study cases centered on logic, data structure, and working backend flows.', 1, 'published', NOW(), NOW()),
('API и backend', 'API and backend', 'api-backend', 'Кейсы, где основное внимание уделено API, обработке запросов и серверной логике.', 'Cases focused on APIs, request handling, and server-side logic.', 2, 'published', NOW(), NOW()),
('Автоматизация', 'Automation', 'automation', 'Небольшие инструменты и утилиты, созданные для сокращения ручной работы и упрощения процессов.', 'Smaller utilities built to reduce manual work and simplify internal processes.', 3, 'published', NOW(), NOW()),
('Web-платформы', 'Web platforms', 'web-platforms', 'Web-сайты, панели управления, dashboard-сценарии и product-oriented интерфейсы.', 'Websites, admin layers, dashboard scenarios, and product-oriented interfaces.', 4, 'published', NOW(), NOW());

INSERT INTO projects (
    category_id, title_ru, title_en, slug, short_description_ru, short_description_en,
    full_description_ru, full_description_en, role_ru, role_en, technologies, external_url, featured, status, sort_order,
    cover_image, cover_alt_ru, cover_alt_en, og_image,
    client_ru, client_en, problem_ru, problem_en, process_ru, process_en, solution_ru, solution_en, result_ru, result_en,
    seo_title_ru, seo_title_en, seo_description_ru, seo_description_en, created_at, updated_at
) VALUES
(
    1, 'Финансовый трекер', 'Finance Tracker', 'finance-tracker',
    'Учебный финальный проект на Go с регистрацией пользователей, транзакциями, фильтрацией и понятной backend-логикой.',
    'A final Go study project with user registration, transactions, filtering, and clear backend logic.',
    'Финансовый трекер был собран как финальный учебный case study, где важно было показать не только знание языка, но и понимание структуры прикладного backend-решения.',
    'Finance Tracker was built as a final study case meant to show more than language basics.',
    'Backend developer - Go / PostgreSQL / Docker', 'Backend developer - Go / PostgreSQL / Docker',
    'Go, PostgreSQL, Docker, REST API', '', 1, 'published', 1,
    'assets/img/project-finance.svg', 'Обложка проекта Финансовый трекер', 'Finance Tracker cover', 'assets/img/project-finance.svg',
    'Финальный учебный кейс, собранный как практическое backend-приложение.', 'A final study case built as a practical backend application.',
    'Нужно было реализовать понятный backend для сценария, где пользователь может зарегистрироваться, добавлять транзакции и фильтровать данные без хаотичной структуры.',
    'The task was to build a clean backend for a workflow where users can register, create transactions, and filter data without a chaotic structure.',
    'Сначала была продумана структура сущностей, сценарии пользователя и базовые API-потоки.',
    'The work started with entity structure, user flows, and API design.',
    'В проекте были реализованы регистрация, добавление и фильтрация транзакций.',
    'The project included registration, transaction creation and filtering.',
    'Кейс стал хорошей практикой backend-мышления.', 'The case became solid backend practice.',
    'Финансовый трекер | Go backend case study', 'Finance Tracker | Go backend case study',
    'Учебный backend-проект на Go с PostgreSQL, Docker и логикой управления транзакциями.',
    'A Go backend case study with PostgreSQL, Docker, and transaction workflows.',
    NOW(), NOW()
),
(
    2, 'Практика REST API', 'REST API Practice', 'rest-api-practice',
    'Практический блок по API, маршрутам, обработке запросов и взаимодействию backend-слоя с данными.',
    'A practice case built around APIs, routing, request handling, and backend interaction with data.',
    'Этот кейс объединяет практику по REST API и небольшим сервисным сценариям.',
    'This case combines REST API practice with smaller service flows.',
    'Backend developer - API practice and service design', 'Backend developer - API practice and service design',
    'Go, REST API, PostgreSQL, Redis, HTTP', '', 1, 'published', 2,
    'assets/img/project-api.svg', 'Обложка проекта Практика REST API', 'REST API Practice cover', 'assets/img/project-api.svg',
    'Практический backend-кейс с акцентом на API и обработку запросов.', 'A backend practice case focused on APIs and request handling.',
    'Нужно было собрать API-сценарии так, чтобы backend вел себя предсказуемо.',
    'The challenge was to shape API flows so that the backend behaved predictably.',
    'Работа строилась вокруг маршрутов, HTTP-поведения, моделей данных, Redis и PostgreSQL.',
    'The work was centered on routes, HTTP behavior, data models, Redis, and PostgreSQL.',
    'В результате был собран набор рабочих backend-сценариев.', 'The result was a set of working backend flows.',
    'Кейс помог лучше выстроить понимание структуры API.', 'The case improved my understanding of API structure.',
    'Практика REST API | Backend и обработка запросов', 'REST API Practice | Backend and request handling',
    'Практический case study по API, маршрутам, Redis, PostgreSQL и server-side логике.',
    'A practical case study focused on APIs, routing, Redis, PostgreSQL, and server-side logic.',
    NOW(), NOW()
),
(
    3, 'Утилиты и автоматизация задач', 'Automation Utilities', 'automation-utilities',
    'Небольшие инструменты на Go и Python для сокращения ручной работы и упрощения повторяющихся сценариев.',
    'Small Go and Python tools built to reduce manual work and simplify repetitive workflows.',
    'Помимо web-проектов, я также работаю над небольшими утилитами и автоматизацией.',
    'Alongside web projects, I also build smaller utilities and automation flows.',
    'Go / Python developer - internal tooling and automation', 'Go / Python developer - internal tooling and automation',
    'Go, Python, HTTP, Git', '', 0, 'published', 3,
    'assets/img/project-automation.svg', 'Обложка проекта Утилиты и автоматизация', 'Automation Utilities cover', 'assets/img/project-automation.svg',
    'Независимые прикладные инструменты и небольшие автоматизационные сценарии.', 'Independent applied tools and smaller automation-oriented workflows.',
    'Задача состояла в том, чтобы убрать ручную рутину.', 'The goal was to remove manual routine.',
    'Работа начиналась с разбора входных данных и сценария.', 'The work started with understanding the input and workflow.',
    'Для таких задач использовались Go и Python.', 'For these tasks I used Go and Python.',
    'Такие кейсы усиливают практический навык разработки.', 'These cases strengthen practical development skills.',
    'Утилиты и автоматизация | Go и Python для внутренних задач', 'Automation Utilities | Go and Python for internal tasks',
    'Небольшие Go и Python утилиты для автоматизации действий и упрощения процессов.',
    'Small Go and Python utilities for automation and workflow simplification.',
    NOW(), NOW()
),
(
    4, 'Axorus Online', 'Axorus Online', 'axorus-online',
    'Live web reference в портфолио с реальной публичной ссылкой и акцентом на production-minded подачу web-платформы.',
    'A live web reference in the portfolio with a real public link and a production-minded presentation of a web platform.',
    'Этот кейс добавлен в портфолио как live reference с реальной публичной ссылкой.',
    'This case is included as a live reference with a real public URL.',
    'Live reference project - public web platform case', 'Live reference project - public web platform case',
    'Web platform, frontend-backend delivery, production presentation', 'https://axorus.online', 1, 'published', 4,
    'assets/img/project-axorus.svg', 'Обложка проекта Axorus Online', 'Axorus Online cover', 'assets/img/project-axorus.svg',
    'Live public reference, включенный в портфолио как пример реальной web-платформы.', 'A live public reference included in the portfolio as an example of a real web platform.',
    'В портфолио было важно показать не только concept-работы, но и реальную публичную ссылку.',
    'It was important to include not only concept work but also a real public link.',
    'Кейс был оформлен как структурированная карточка с ролью, описанием, визуальной обложкой и переходом.',
    'The case was framed as a structured portfolio entry with a role, description, visual cover, and a link.',
    'В результате проект усиливает публичную часть портфолио.', 'As a result, the project strengthens the public side of the portfolio.',
    'Кейс делает портфолио убедительнее.', 'The case makes the portfolio more convincing.',
    'Axorus Online | Live web reference', 'Axorus Online | Live web reference',
    'Live reference project with a real public URL included in the portfolio.',
    'Live reference project with a real public URL included in the portfolio.',
    NOW(), NOW()
),
(
    4, 'GitHub Code Archive', 'GitHub Code Archive', 'github-code-archive',
    'Публичный архив GitHub с backend-проектами, утилитами и production-minded примерами.',
    'A public GitHub archive with backend projects, utilities, and production-minded examples.',
    'Этот проект представляет собой curated архив на GitHub, где собраны мои backend-репозитории.',
    'This project is a curated GitHub archive containing my backend repositories.',
    'Repository showcase - backend, tools, and portfolio examples', 'Repository showcase - backend, tools, and portfolio examples',
    'Git, Go, PHP, Python, Docker', 'https://github.com/fakha2009', 1, 'published', 8,
    'assets/img/project-api.svg', 'Обложка проекта GitHub Code Archive', 'GitHub Code Archive cover', 'assets/img/project-api.svg',
    'Публичная коллекция репозиториев и backend-работ.', 'A public collection of repositories and backend work.',
    'Задача состояла в показать не только рабочие кейсы, но и сам способ организации кода.',
    'The task was to show not only working cases but also the way code is organized.',
    'Сначала я собрал набор релевантных репозиториев.', 'First I assembled a set of relevant repositories.',
    'Решение состоит в удобном entry-point для GitHub-аудитории.', 'The solution is a convenient entry point for GitHub audiences.',
    'В результате получилось портфолио-ссылку на живой GitHub.', 'As a result, the portfolio gains a live GitHub link.',
    'GitHub Code Archive | Public repository showcase', 'GitHub Code Archive | Public repository showcase',
    'Публичный GitHub-архив с backend-проектами и примерами production-minded кода.',
    'A public GitHub archive with backend projects and production-minded code examples.',
    NOW(), NOW()
),
(
    4, 'Operations Dashboard Concept', 'Operations Dashboard Concept', 'operations-dashboard-concept',
    'Concept-кейс по dashboard-системе с акцентом на статусные панели, админскую логику и data-driven подачу.',
    'A concept case focused on a dashboard system with status panels, admin logic, and data-driven presentation.',
    'Этот проект оформлен как concept case study по внутренней dashboard-системе.',
    'This project is presented as a concept case study for an internal dashboard system.',
    'PHP developer - dashboard and admin architecture concept', 'PHP developer - dashboard and admin architecture concept',
    'PHP, MySQL, Chart.js, Admin UI, Data flows', '', 1, 'published', 5,
    'assets/img/project-admin.svg', 'Обложка проекта Operations Dashboard Concept', 'Operations Dashboard Concept cover', 'assets/img/project-admin.svg',
    'Concept-платформа для внутренних операций и административного контроля.', 'A concept platform for internal operations and administrative control.',
    'Нужно было показать, как выглядит сильная backend-ориентированная dashboard-система.',
    'The goal was to show what a strong backend-oriented dashboard system looks like.',
    'Сначала была продумана структура сущностей, метрик и ролей.',
    'The work began with entity, metric, and role structure.',
    'В результате получился concept-кейс, который показывает подход к data-driven интерфейсам.',
    'The result is a concept case that demonstrates an approach to data-driven interfaces.',
    'Кейс усиливает портфолио в части dashboard и SaaS-like подачи.', 'This case strengthens the portfolio in the dashboard and SaaS-like presentation direction.',
    'Operations Dashboard Concept | Admin system case study', 'Operations Dashboard Concept | Admin system case study',
    'Concept case study for a dashboard and admin-oriented platform.',
    'Concept case study for a dashboard and admin-oriented platform.',
    NOW(), NOW()
),
(
    4, 'Portfolio Control Platform', 'Portfolio Control Platform', 'portfolio-control-platform',
    'PHP-кейс по bilingual portfolio-сайту со скрытой admin-панелью, формами, аналитикой и shared-hosting-friendly архитектурой.',
    'A PHP case study for a bilingual portfolio site with a hidden admin panel, forms, analytics, and shared-hosting-friendly architecture.',
    'Этот проект отражает текущую платформу портфолио: public-сайт, скрытая admin-панель, first-party analytics.',
    'This project reflects the current portfolio platform: public website, hidden admin panel, first-party analytics.',
    'PHP developer - portfolio CMS and hidden admin platform', 'PHP developer - portfolio CMS and hidden admin platform',
    'PHP, MySQL, PDO, PHPMailer, Chart.js, Cloudinary', '', 0, 'published', 6,
    'assets/img/project-nova.svg', 'Обложка проекта Portfolio Control Platform', 'Portfolio Control Platform cover', 'assets/img/project-nova.svg',
    'Собственная платформа портфолио с public-сайтом и скрытой админкой.', 'A portfolio platform with a public website and a hidden admin area.',
    'Нужно было собрать премиальную web-витрину и одновременно сохранить практичную административную часть.',
    'The task was to build a premium public presentation while keeping a practical admin layer.',
    'Проект строился вокруг модульного PHP-кода, MySQL, безопасной аутентификации.',
    'The project was built around modular PHP, MySQL, secure authentication.',
    'В результате получилась управляемая платформа.', 'The result is a manageable platform.',
    'Кейс хорошо показывает подход к реальной реализации на PHP.', 'The case shows a practical PHP implementation approach.',
    'Portfolio Control Platform | PHP portfolio CMS case study', 'Portfolio Control Platform | PHP portfolio CMS case study',
    'Bilingual PHP portfolio platform with hidden admin panel, analytics, and shared-hosting-ready architecture.',
    'Bilingual PHP portfolio platform with hidden admin panel, analytics, and shared-hosting-ready architecture.',
    NOW(), NOW()
),
(
    2, 'Backend Monitoring API', 'Backend Monitoring API', 'backend-monitoring-api',
    'Concept-кейс по API-сервису для событий, статусов и технического мониторинга системных процессов.',
    'A concept case for an API service that handles events, statuses, and technical monitoring flows.',
    'Этот кейс оформлен как backend-oriented concept project для мониторинга событий и системных статусов.',
    'This case is framed as a backend-oriented concept project for monitoring events and system states.',
    'Backend developer - monitoring and event ingestion concept', 'Backend developer - monitoring and event ingestion concept',
    'Go, HTTP, REST API, MySQL, Redis', '', 0, 'published', 7,
    'assets/img/project-signal.svg', 'Обложка проекта Backend Monitoring API', 'Backend Monitoring API cover', 'assets/img/project-signal.svg',
    'Concept-сервис для технических событий, статусов и внутреннего наблюдения за процессами.', 'A concept service for technical events, statuses, and internal process visibility.',
    'Нужно было показать, как может выглядеть компактный API-сервис.',
    'The goal was to show how a compact API service can accept events.',
    'Логика кейса строилась вокруг модели событий, структуры хранилища, HTTP-endpoints.',
    'The case was shaped around an event model, storage structure, HTTP endpoints.',
    'В результате получился concept-кейс по service design.', 'The result is a service-design concept.',
    'Кейс помогает показать, как backend может работать не только с обычными CRUD-задачами.',
    'The case helps show how backend work can go beyond CRUD into system signals.',
    'Backend Monitoring API | API and system signals concept', 'Backend Monitoring API | API and system signals concept',
    'Concept case study for an API service focused on events, statuses, and monitoring flows.',
    'Concept case study for an API service focused on events, statuses, and monitoring flows.',
    NOW(), NOW()
);

INSERT INTO project_images (project_id, file_path, thumb_path, alt_ru, alt_en, is_cover, sort_order, created_at) VALUES
(1, 'assets/img/project-finance.svg', 'assets/img/project-finance.svg', 'Финансовый трекер', 'Finance Tracker', 1, 1, NOW()),
(1, 'assets/img/project-signal.svg', 'assets/img/project-signal.svg', 'Дополнительный визуал Финансовый трекер', 'Finance Tracker supporting visual', 0, 2, NOW()),
(2, 'assets/img/project-api.svg', 'assets/img/project-api.svg', 'Практика REST API', 'REST API Practice', 1, 1, NOW()),
(2, 'assets/img/project-signal.svg', 'assets/img/project-signal.svg', 'Дополнительный визуал Практика REST API', 'REST API Practice supporting visual', 0, 2, NOW()),
(3, 'assets/img/project-automation.svg', 'assets/img/project-automation.svg', 'Утилиты и автоматизация', 'Automation Utilities', 1, 1, NOW()),
(3, 'assets/img/project-nova.svg', 'assets/img/project-nova.svg', 'Дополнительный визуал Утилиты и автоматизация', 'Automation Utilities supporting visual', 0, 2, NOW()),
(4, 'assets/img/project-axorus.svg', 'assets/img/project-axorus.svg', 'Axorus Online', 'Axorus Online', 1, 1, NOW()),
(4, 'assets/img/project-nova.svg', 'assets/img/project-nova.svg', 'Дополнительный визуал Axorus Online', 'Axorus Online supporting visual', 0, 2, NOW()),
(5, 'assets/img/project-admin.svg', 'assets/img/project-admin.svg', 'Operations Dashboard Concept', 'Operations Dashboard Concept', 1, 1, NOW()),
(5, 'assets/img/project-signal.svg', 'assets/img/project-signal.svg', 'Дополнительный визуал Operations Dashboard Concept', 'Operations Dashboard Concept supporting visual', 0, 2, NOW()),
(6, 'assets/img/project-nova.svg', 'assets/img/project-nova.svg', 'Portfolio Control Platform', 'Portfolio Control Platform', 1, 1, NOW()),
(6, 'assets/img/project-admin.svg', 'assets/img/project-admin.svg', 'Дополнительный визуал Portfolio Control Platform', 'Portfolio Control Platform supporting visual', 0, 2, NOW()),
(7, 'assets/img/project-signal.svg', 'assets/img/project-signal.svg', 'Backend Monitoring API', 'Backend Monitoring API', 1, 1, NOW()),
(7, 'assets/img/project-api.svg', 'assets/img/project-api.svg', 'Дополнительный визуал Backend Monitoring API', 'Backend Monitoring API supporting visual', 0, 2, NOW());
